In [1]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [2]:
digits= load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest= train_test_split(digits.data,digits.target,test_size=0.3)

In [5]:
len(xtrain),len(xtest)

(1257, 540)

In [20]:
#Logistic Regression
lr= LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(xtrain,ytrain)
lr.score(xtest,ytest)

0.9592592592592593

In [19]:
#SVM
svm= SVC(gamma='auto')
svm.fit(xtrain,ytrain)
svm.score(xtest,ytest)

0.4462962962962963

In [21]:
#Random Forest
rf = RandomForestClassifier(n_estimators=40)
rf.fit(xtrain, ytrain)
rf.score(xtest, ytest)

0.9666666666666667

# K Fold Classification

Sample K Fold Classification

In [23]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
for train_index, test_index in kf.split([0,1,2,3,4,5,6,7,8]):
  print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


K Fold Classification for Digits Example

In [29]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [31]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

scores_logistic= []
scores_svm= []
scores_rf= []

for train_index, test_index in folds.split(digits.data,digits.target):
  xtrain, xtest, ytrain, ytest= digits.data[train_index], digits.data[test_index],\
                                digits.target[train_index], digits.target[test_index]
  scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), xtrain, xtest, ytrain, ytest))  
  scores_svm.append(get_score(SVC(gamma='auto'), xtrain, xtest, ytrain, ytest))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),xtrain, xtest, ytrain, ytest))

In [32]:
scores_logistic, scores_svm, scores_rf

([0.8948247078464107, 0.9532554257095158, 0.9098497495826378],
 [0.3806343906510851, 0.41068447412353926, 0.5125208681135225],
 [0.9382303839732888, 0.9582637729549248, 0.9215358931552587])

# Using cross_val_score function

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
#Logistic Regression
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [36]:
#SVM
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [37]:
#Random Forest
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.91986644, 0.95158598, 0.93823038])

cross_val_score uses StratifiedKFold by default

**Parameter Tuning using K Fold Cross Validation**

In [38]:
import numpy as np

In [39]:
scores1= cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)
np.mean(scores1)

0.9193099610461881

In [40]:
scores2= cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)
np.mean(scores2)

0.4346132442960489

In [43]:
scores3= cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target,cv=3)
np.mean(scores3)

0.8619922092376182

In [44]:
scores4= cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target,cv=3)
np.mean(scores4)

0.9226488592097941

In [45]:
scores3= cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target,cv=3)
np.mean(scores3)

0.9232053422370617

In [46]:
scores3= cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)
np.mean(scores3)

0.9259877573734001